
name: Run Selenium on Ubuntu

on:
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        go: [1.16, 1.17]
        flag: [A, B]
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium

      - name: Run Python script
        run: |
          python3 run.py
